<?php
echo "Im Kontext des Querthemas hinsichtlich der Sicherheit können folgende Punkte genannt werden:<br><br><br>";
echo "Sicherheit in PHP:";
echo "<ul>";
echo "<li>";
echo "Passwörter sicher speichern";
echo "<ul>";
echo "<li>password_hash() zum Hashen von Passwörtern verwenden.</li>";
echo "<li>password_verify() zum Überprüfen von Passwörtern verwenden.</li>";
echo "<li>Keine Passwörter im Klartext speichern.</li>";
echo "</ul>";
echo "</li>";
echo "<li>";
echo "SQL-Injection vehindern";
echo "<ul>";
echo "<li>Prepared Statements mit PDO oder MySQLi verwenden.</li>";
echo "<li>Benutzereingaben niemals direkt in SQL-Abfragen einfügen.</li>";
echo "</ul>";
echo "</li>";
echo "<li>";
echo "Cross-Site Scripting (XSS) verhindern";
echo "<ul>";
echo "<li>Benutzereingaben vor der Ausgabe mit htmlspecialchars() maskieren.</li>";
echo "</ul>";
echo "</li>";
echo "<li>";
echo "Benutzereingaben validieren";
echo "<ul>";
echo "<li>Eingaben auf Format und Inhalt prüfen.</li>";
echo "</ul>";
echo "</li>";
echo "<li>";
echo "Datei-Uploads absichern";
echo "<ul>";
echo "<li>Dateityp und Dateigröße prüfen.</li>";
echo "<li>Hochgeladene Dateien außerhalb des öffentlich erreichbaren Webverzeichnisses speichern.</li>";
echo "</ul>";
echo "</li>";
echo "<li>";
echo "Sitzungen (Sessions) schützen";
echo "<ul>";
echo "<li>Session-ID nach der Anmeldung mit session_regenerate_id() erneuern.</li>";
echo "<li>Sichere Session-Cookies verwenden (passiert automatisch, wenn neu angemeldet wird, nachdem der Browser geschlossen wurde.</li>";
echo "</ul>";
echo "</li>";
echo "<li>";
echo "Fehlermeldungen";
echo "<ul>";
echo "<li>In Produktivsystemen keine detaillierten Fehlermeldungen anzeigen.</li>";
echo "<li>Fehler in Logdateien protokolieren.</li>";
echo "</ul>";
echo "</li>";
echo "<li>";
echo "Aktuellste Version verwenden";
echo "<ul>";
echo "<li>Regelmäßig Sicherheitsupdates installieren.</li>";
echo "<li>Veraltete PHP-Versionen vermeiden.</li>";
echo "</ul>";
echo "</li>";
echo "</ul>";

?>

